version: 0.2
env:
  variables:
    NEXT_PUBLIC_API_BASE_URL: "https://c301gwdbok.execute-api.us-east-2.amazonaws.com/Prod"
    NEXT_PUBLIC_CDN_URL: "https://d3ay3etzd1512y.cloudfront.net"
    NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyD-v_UwJpyY2aVYS7yVt3E8MXLl-H3IYVg"
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "creditodds.firebaseapp.com"
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: "creditodds"
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "creditodds.firebasestorage.app"
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "1064564569219"
    NEXT_PUBLIC_FIREBASE_APP_ID: "1:1064564569219:web:9f7c5be4b05426aeaafeef"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Debug: list directory structure
      - ls -la
      - ls -la apps/
      # Install dependencies using npm workspaces
      - npm ci
  build:
    commands:
      # Build the Next.js app using workspace command
      - npm run build:web-next
  post_build:
    commands:
      - aws s3 sync apps/web-next/out/ s3://creditodds-website/ --delete
      - aws cloudfront create-invalidation --distribution-id ECS8QY2GQ641I --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: apps/web-next/out
