version: 0.2
# Environment variables are configured in AWS CodeBuild project settings
# Required variables:
#   - NEXT_PUBLIC_API_BASE_URL
#   - NEXT_PUBLIC_CDN_URL
#   - NEXT_PUBLIC_FIREBASE_API_KEY
#   - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
#   - NEXT_PUBLIC_FIREBASE_PROJECT_ID
#   - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
#   - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
#   - NEXT_PUBLIC_FIREBASE_APP_ID
#   - S3_BUCKET_NAME
#   - CLOUDFRONT_DISTRIBUTION_ID
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install dependencies using npm workspaces
      - npm ci
  build:
    commands:
      # Build the Next.js app using workspace command
      - npm run build:web-next
  post_build:
    commands:
      - aws s3 sync apps/web-next/out/ s3://${S3_BUCKET_NAME}/ --delete
      # Invalidate CloudFront cache (non-blocking if it fails)
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*" || echo "CloudFront invalidation failed - cache may not be cleared"
artifacts:
  files:
    - '**/*'
  base-directory: apps/web-next/out
