-- Standardize card names: remove "Card" and "Credit Card" suffixes
-- Slugs and card_ids are unchanged

UPDATE cards SET card_name = 'Aer Lingus Visa Signature' WHERE card_name = 'Aer Lingus Visa Signature card';
UPDATE cards SET card_name = 'Amazon Business Prime American Express' WHERE card_name = 'Amazon Business Prime American Express Card';
UPDATE cards SET card_name = 'Amazon Prime Rewards Visa Signature' WHERE card_name = 'Amazon Prime Rewards Visa Signature Card';
UPDATE cards SET card_name = 'American Express Business Gold' WHERE card_name = 'American Express Business Gold Card';
UPDATE cards SET card_name = 'American Express Gold' WHERE card_name = 'American Express Gold Card';
UPDATE cards SET card_name = 'American Express Green' WHERE card_name = 'American Express Green Card';
UPDATE cards SET card_name = 'Amex Everyday' WHERE card_name = 'Amex Everyday Credit Card';
UPDATE cards SET card_name = 'Amex Everyday Preferred' WHERE card_name = 'Amex Everyday Preferred Credit Card';
UPDATE cards SET card_name = 'AT&T Access from Citi' WHERE card_name = 'AT&T Access Card From Citi';
UPDATE cards SET card_name = 'Bank of America Cash Rewards Secured' WHERE card_name = 'Bank of America Cash Rewards Secured Credit Card';
UPDATE cards SET card_name = 'Bank of America Customized Cash Rewards' WHERE card_name = 'Bank of America Customized Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Bank of America Premium Rewards Elite' WHERE card_name = 'Bank of America Premium Rewards Elite Credit Card';
UPDATE cards SET card_name = 'Bank of America Premium Rewards' WHERE card_name = 'Bank of America Premium Rewards Credit Card';
UPDATE cards SET card_name = 'Bank of America Travel Rewards' WHERE card_name = 'Bank of America Travel Rewards Credit Card';
UPDATE cards SET card_name = 'Bank of America Unlimited Cash Rewards' WHERE card_name = 'Bank of America Unlimited Cash Rewards Credit Card';
UPDATE cards SET card_name = 'BankAmericard' WHERE card_name = 'BankAmericard Credit Card';
UPDATE cards SET card_name = 'Blue Business Cash from American Express' WHERE card_name = 'Blue Business Cash Card from American Express';
UPDATE cards SET card_name = 'Blue Business Plus from American Express' WHERE card_name = 'Blue Business Plus Credit Card from American Express';
UPDATE cards SET card_name = 'Blue Cash Everyday' WHERE card_name = 'Blue Cash Everyday Card';
UPDATE cards SET card_name = 'Blue Cash Preferred' WHERE card_name = 'Blue Cash Preferred Card';
UPDATE cards SET card_name = 'British Airways Visa Signature' WHERE card_name = 'British Airways Visa Signature card';
UPDATE cards SET card_name = 'Capital One Platinum Secured' WHERE card_name = 'Capital One Platinum Secured Credit Card';
UPDATE cards SET card_name = 'Capital One Platinum' WHERE card_name = 'Capital One Platinum Credit Card';
UPDATE cards SET card_name = 'Capital One Quicksilver Secured Cash Rewards' WHERE card_name = 'Capital One Quicksilver Secured Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One Quicksilver Cash Rewards' WHERE card_name = 'Capital One Quicksilver Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One QuicksilverOne Cash Rewards' WHERE card_name = 'Capital One QuicksilverOne Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One Savor Student Cash Rewards' WHERE card_name = 'Capital One Savor Student Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One Savor Cash Rewards' WHERE card_name = 'Capital One Savor Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One SavorOne Cash Rewards' WHERE card_name = 'Capital One SavorOne Cash Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One Venture Rewards' WHERE card_name = 'Capital One Venture Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One Venture X Rewards' WHERE card_name = 'Capital One Venture X Rewards Credit Card';
UPDATE cards SET card_name = 'Capital One VentureOne Rewards' WHERE card_name = 'Capital One VentureOne Rewards Credit Card';
UPDATE cards SET card_name = 'Cash Magnet' WHERE card_name = 'Cash Magnet Card';
UPDATE cards SET card_name = 'IHG One Rewards Premier Business' WHERE card_name = 'IHG One Rewards Premier Business Credit Card';
UPDATE cards SET card_name = 'Ink Business Cash' WHERE card_name = 'Ink Business Cash Credit Card';
UPDATE cards SET card_name = 'Ink Business Preferred' WHERE card_name = 'Ink Business Preferred Credit Card';
UPDATE cards SET card_name = 'Ink Business Unlimited' WHERE card_name = 'Ink Business Unlimited Credit Card';
UPDATE cards SET card_name = 'Chase Sapphire Preferred' WHERE card_name = 'Chase Sapphire Preferred Card';
UPDATE cards SET card_name = 'Citi Strata Elite' WHERE card_name = 'Citi Strata Elite Card';
UPDATE cards SET card_name = 'Citi Strata Premier' WHERE card_name = 'Citi Strata Premier Card';
UPDATE cards SET card_name = 'Citi Strata' WHERE card_name = 'Citi Strata Card';
UPDATE cards SET card_name = 'Costco Anywhere Visa Business by Citi' WHERE card_name = 'Costco Anywhere Visa Business Card by Citi';
UPDATE cards SET card_name = 'Costco Anywhere Visa by Citi' WHERE card_name = 'Costco Anywhere Visa Card by Citi';
UPDATE cards SET card_name = 'Delta SkyMiles Blue American Express' WHERE card_name = 'Delta SkyMiles Blue American Express Card';
UPDATE cards SET card_name = 'Delta SkyMiles Gold American Express' WHERE card_name = 'Delta SkyMiles Gold American Express Card';
UPDATE cards SET card_name = 'Delta SkyMiles Platinum American Express' WHERE card_name = 'Delta SkyMiles Platinum American Express Card';
UPDATE cards SET card_name = 'Delta SkyMiles Reserve American Express' WHERE card_name = 'Delta SkyMiles Reserve American Express Card';
UPDATE cards SET card_name = 'Discover it for Students' WHERE card_name = 'Discover it for Students Card';
UPDATE cards SET card_name = 'Discover it Secured' WHERE card_name = 'Discover it Secured Credit Card';
UPDATE cards SET card_name = 'Discover it Student Chrome' WHERE card_name = 'Discover it Student Chrome Card';
UPDATE cards SET card_name = 'Disney Inspire Visa' WHERE card_name = 'Disney Inspire Visa Card';
UPDATE cards SET card_name = 'Disney Premier Visa' WHERE card_name = 'Disney Premier Visa Card';
UPDATE cards SET card_name = 'Disney Visa' WHERE card_name = 'Disney Visa Card';
UPDATE cards SET card_name = 'Expedia Rewards from Citi' WHERE card_name = 'Expedia Rewards Card from Citi';
UPDATE cards SET card_name = 'Expedia Rewards Voyager from Citi' WHERE card_name = 'Expedia Rewards Voyager Card from Citi';
UPDATE cards SET card_name = 'Hilton Honors American Express Aspire' WHERE card_name = 'Hilton Honors American Express Aspire Card';
UPDATE cards SET card_name = 'Hilton Honors American Express Surpass' WHERE card_name = 'Hilton Honors American Express Surpass Card';
UPDATE cards SET card_name = 'Hilton Honors' WHERE card_name = 'Hilton Honors Card';
UPDATE cards SET card_name = 'Iberia Visa Signature' WHERE card_name = 'Iberia Visa Signature card';
UPDATE cards SET card_name = 'IHG One Rewards Premier' WHERE card_name = 'IHG One Rewards Premier Credit Card';
UPDATE cards SET card_name = 'IHG Rewards Club Traveler' WHERE card_name = 'IHG Rewards Club Traveler Credit Card';
UPDATE cards SET card_name = 'JetBlue Business' WHERE card_name = 'JetBlue Business Card';
UPDATE cards SET card_name = 'JetBlue' WHERE card_name = 'JetBlue Card';
UPDATE cards SET card_name = 'JetBlue Plus' WHERE card_name = 'JetBlue Plus Card';
UPDATE cards SET card_name = 'Marriott Bonvoy Bold' WHERE card_name = 'Marriott Bonvoy Bold Credit Card';
UPDATE cards SET card_name = 'Marriott Bonvoy Boundless' WHERE card_name = 'Marriott Bonvoy Boundless credit card';
UPDATE cards SET card_name = 'Princess Cruises Rewards Visa' WHERE card_name = 'Princess Cruises Rewards Visa Card';
UPDATE cards SET card_name = 'Southwest Rapid Rewards Plus' WHERE card_name = 'Southwest Rapid Rewards Plus Credit Card';
UPDATE cards SET card_name = 'Southwest Rapid Rewards Premier' WHERE card_name = 'Southwest Rapid Rewards Premier Credit Card';
UPDATE cards SET card_name = 'Southwest Rapid Rewards Priority' WHERE card_name = 'Southwest Rapid Rewards Priority Credit Card';
UPDATE cards SET card_name = 'Starbucks Rewards Visa' WHERE card_name = 'Starbucks Rewards Visa Card';
UPDATE cards SET card_name = 'U.S. Bank Altitude Go Visa Signature' WHERE card_name = 'U.S. Bank Altitude Go Visa Signature Card';
UPDATE cards SET card_name = 'U.S. Bank Altitude Reserve Visa Infinite' WHERE card_name = 'U.S. Bank Altitude Reserve Visa Infinite Card';
UPDATE cards SET card_name = 'U.S. Bank Cash+ Visa Signature' WHERE card_name = 'U.S. Bank Cash+ Visa Signature Card';
UPDATE cards SET card_name = 'Smartly Visa Signature' WHERE card_name = 'Smartly Visa Signature Card';
UPDATE cards SET card_name = 'Wells Fargo Active Cash' WHERE card_name = 'Wells Fargo Active Cash Card';
UPDATE cards SET card_name = 'Wells Fargo Attune' WHERE card_name = 'Wells Fargo Attune Card';
UPDATE cards SET card_name = 'Wells Fargo Autograph Journey' WHERE card_name = 'Wells Fargo Autograph Journey Card';
UPDATE cards SET card_name = 'Wells Fargo Autograph' WHERE card_name = 'Wells Fargo Autograph Card';
UPDATE cards SET card_name = 'Wells Fargo Reflect' WHERE card_name = 'Wells Fargo Reflect Card';
UPDATE cards SET card_name = 'Wells Fargo Signify Business Cash' WHERE card_name = 'Wells Fargo Signify Business Cash Card';
UPDATE cards SET card_name = 'World of Hyatt Business' WHERE card_name = 'World of Hyatt Business Credit Card';
UPDATE cards SET card_name = 'World of Hyatt' WHERE card_name = 'World of Hyatt Credit Card';
UPDATE cards SET card_name = 'Wyndham Rewards Earner Business' WHERE card_name = 'Wyndham Rewards Earner Business Card';
UPDATE cards SET card_name = 'Wyndham Rewards Earner' WHERE card_name = 'Wyndham Rewards Earner Card';
UPDATE cards SET card_name = 'Wyndham Rewards Earner Plus' WHERE card_name = 'Wyndham Rewards Earner Plus Card';
